### PR TITLE
Update presentation.md with urls

### PR DESCRIPTION
**Pull request by heratyian**

### CODE REVIEW

**Comment by aldoportillo** [comment]
Looks Good To Me!

**Review by aldoportillo — APPROVED** [review]

**Review by aldoportillo — CHANGES_REQUESTED** [review]
Should we format these such that we can just input a link:

- [Slides URL]()

**Comment by heratyian** [comment]
> Should we format these such that we can just input a link:
> 
> * Slides URL

up to the grader. i don't mind having the raw url for things like domain url.

**Comment by heratyian** [comment]
seems like i botched an earlier PR, take a look @aldoportillo

**Pull request merged**
